# Generated by Django 6.0.4 on 2026-05-07 19:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=15)),
                ('espacio', models.CharField(max_length=50)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='cobro.cliente')),
            ],
            options={
                'verbose_name': 'Cobro de Estacionamiento',
                'verbose_name_plural': 'Cobros de Estacionamiento',
            },
        ),
    ]
